// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  parallax: dynamic(() => import("./Parallax")),
  product_grid: dynamic(() => import("./ProductGrid")),
  video_block: dynamic(() => import("./VideoBlock")),
};
